### PR TITLE
Implementation of Devise Authentication and Views

### PR DESCRIPTION
**Pull request by Zafron047**
## Dear Reviewer,
This pull request implements authentication using Devise and updates the views for registration and login to match the wireframes provided in the Sneak Peek document. The changes and additions made in this pull request are as follows:

### Project requirements
- Remove `current_user` method in `ApplicationController`, devise will provide us with one.
- [Install and setup devise](https://github.com/heartcombo/devise#getting-started).
  - Can register a new user.
  - User logs in with a combination of email and password.
  - Hashed password should be stored in the database.
  - Ask for confirmation of email.
  - Can reset password.
- Modify the views in devise for registration and login to match the wireframes from the Sneak Peek with:
  - rails generate devise:views users
  - rails generate devise:controllers Users.

#### Changes Made

1. Removed the `current_user` method from `ApplicationController` as Devise provides this functionality.

2. Installed and set up Devise using the guidelines from [Devise Getting Started](https://github.com/heartcombo/devise#getting-started).

3. Implemented the following Devise features:
   - User registration.
   - User login using a combination of email and password.
   - Confirmation of email during registration.
   - Password reset functionality.

4. Modified the views for registration and login by generating Devise views and controllers for the `Users` resource.

#### Screenshots
registration
---
</br>

log_in
---
</br>

pass_reset
---
</br>

#### Additional Information
The views have been updated to match the wireframes provided in the Sneak Peek document, ensuring a consistent and user-friendly interface.

Please review and merge this pull request to incorporate these changes into the project.

Thanking you!

@Zafron047

### CODE REVIEW

**Comment by Zafron047** [comment]
# Attn: Dear Reviewer
**This comment is temporary.** I cannot find my peer to collaborate and I am already behind 1 day. So I had to let microverse know about this situation and thus I have finally submitted solo.

Please take this situation into your kind consideration and thank you for the review.

**Review by V-Blaze — CHANGES_REQUESTED** [review]
Hi @Zafron047 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

dcentl8-9b96e129-9725-401b-ac34-2feb990202a0

## Invalid Code Review Request

##You have submitted a project, that doesn't have commits and contributions from your partner.

## I noticed you've made good progress on the project even though your pair wasn't available. But as required, this is a pair programming activity and your partner needs to contribute meaningfully to this branch. Since your partner is not responding, You need to get written approval from the student success to work solo on your activities. please do well to attach a screenshot of that approval to this pull request before requesting for another review...

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by uwadonat — APPROVED** [review]
## Hi @Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- Good commit messages ✔️
- Well-organized and clean project ✔️
- Detailed pull request message ✔️
- No linter errors ✔️
approv

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Zafron047** [comment]
@uwadonat Thanks for the review.

**Pull request merged**
